apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: acmefit
    service: frontend
spec:
  ports:
    - name: http-frontend
      protocol: TCP
      port: 80
      targetPort: 3000
        #nodePort: 30430
  selector:
    app: acmefit
    service: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: acmefit
    service: frontend
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  selector:
    matchLabels:
      app: acmefit
      service: frontend
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: acmefit
        service: frontend
    spec:
      containers:
      - image: postout7979/acmeshop-front-end:latest
        name: frontend
        env:
        - name: FRONTEND_PORT
          value: '3000'
        - name: USERS_HOST
          value: 'users'
        - name: CATALOG_HOST
          value: 'catalog'
        - name: ORDER_HOST
          value: 'order'
        - name: CART_HOST
          value: 'cart'
        - name: USERS_PORT
          value: '8083'
        - name: CATALOG_PORT
          value: '8082'
        - name: CART_PORT
          value: '5000'
        - name: ORDER_PORT
          value: '6000'
        - name: JAEGER_AGENT_HOST
          value: 'localhost'
        - name: JAEGER_AGENT_PORT
          value: '6832'
        ports:
        - containerPort: 3000
          name: frontend
        readinessProbe:
        # -- Minimum consecutive failures for the [probe] to be considered failed after having succeeded. The default is 3.
          failureThreshold: 3
          httpGet:
            path: /abc/
            port: 3000
            scheme: HTTP
          # -- Number of seconds after the container has started before [probe] is initiated. The default is 0.
          initialDelaySeconds: 3
          # -- How often (in seconds) to perform the [probe]. The default is 10.
          periodSeconds: 3
          # -- Minimum consecutive successes for the [probe] to be considered successful after having failed. The default is 1.
          successThreshold: 1
          timeoutSeconds: 1

        lifecycle:
          preStop:
            exec:
              command: ["sleep 10"]
      terminationGracePeriodSeconds: 30


